export const investmentMonthlyData = [
    {
      title: "Eyes of the future A1",
      investAmount: "₹ 599",
      productCode: "EA1",
      earnings: "₹ 5000",
      returnPeriod: "1 Month",
      periodicReturn: "₹ 5000",
      totalEarnings: "₹ 5000",
    },
    {
      title: "Eyes of the future A2",
      investAmount: "₹ 1999",
      productCode: "EA2",
      earnings: "₹ 15,000",
      returnPeriod: "1 Month",
      periodicReturn: "₹ 15,000",
      totalEarnings: "₹ 15,000",
    },
    {
      title: "Eyes of the future A3",
      investAmount: "₹ 50,000",
      productCode: "EA3",
      earnings: "₹ 1,80,000",
      returnPeriod: "1 Month",
      periodicReturn: "₹ 1,80,000",
      totalEarnings: "₹ 1,80,000",
    },
  ];
  
export const investmentData = [
    [
      {
        title: "Daily income A",
        investAmount: "₹ 300",
        totalEarnings: "₹ 1500",
        productCode: "DA",
        returnPeriod: "30 Day",
        periodicReturn: "₹ 50",
        earningChances: "0 / 30",
        buttonText: "Invest Now >",
        buttonColor: "#3babd9",
        textColor: "#fff",
      },
      {
        title: "Monthly income A",
        investAmount: "₹ 1000",
        totalEarnings: "₹ 4100",
        productCode: "MA",
        returnPeriod: "1 Month",
        periodicReturn: "₹4100",
        earningChances: "0 / 1",
        buttonText: "Not activated",
        buttonColor: "#fff",
        textColor: "#FFC107",
        disabled: true,
      },
    ],
    [
      {
        title: "Daily income B",
        investAmount: "₹ 800",
        totalEarnings: "₹ 3450",
        productCode: "DB",
        returnPeriod: "30 Day",
        periodicReturn: "₹ 115",
        earningChances: "0 / 30",
        buttonText: "Invest Now >",
        buttonColor: "#3babd9",
        textColor: "#fff",
      },
      {
        title: "Monthly income B",
        investAmount: "₹ 5000",
        totalEarnings: "₹ 21,000",
        productCode: "MB",
        returnPeriod: "1 Month",
        periodicReturn: "₹21,000",
        earningChances: "0 / 1",
        buttonText: "Not activated",
        buttonColor: "#fff",
        textColor: "#FFC107", 
        disabled: true,
      },
    ],
    [
      {
        title: "Daily income C",
        investAmount: "₹ 20,000",
        totalEarnings: "₹ 55,000",
        productCode: "DC",
        returnPeriod: "30 Day",
        periodicReturn: "₹ 1833",
        earningChances: "0 / 30",
        buttonText: "Invest Now >",
        buttonColor: "#3babd9",
        textColor: "#fff",
      },
      {
        title: "Monthly income C",
        investAmount: "₹ 10,000",
        totalEarnings: "₹ 70,000",
        productCode: "MC",
        returnPeriod: "1 Month",
        periodicReturn: "₹70,000",
        earningChances: "0 / 1",
        buttonText: "Not activated",
        buttonColor: "#fff",
        textColor: "#FFC107", 
        disabled: true,
      },
    ],
  ];